[build]
  command = "rm -rf netlify/functions/backend && cp -r backend netlify/functions/ && cd frontend && npm ci && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"



[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
